version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  node-install:
    resource_class: medium
    docker:
      - image: cimg/ruby:2.7.4
    steps:
      - node/install:
          install-yarn: true
          node-version: 16.18.1

workflows:
  main:
    jobs:
      - node-install